INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (1, N'You.mp3', 1968, N'Marvin Gaye')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (2, N'Trouble Man.mp3', 1972, N'Marvin Gaye')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (3, N'Inner city blues.mp3', 1971, N'Marvin Gaye')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (4, N'Boogie on Reggae Woman.mp3', 1974, N'Stevie Wonder')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (5, N'I Wish.mp3', 1972, N'Stevie Wonder')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (6, N'For Once in My Life.mp3', 1968, N'Stevie Wonder')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (7, N'Living for the City.mp3', 1973, N'Stevie Wonder')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (8, N'Master Blaster (Jammin_).mp3', 1980, N'tevie Wonder')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (9, N'Signed, Sealed, Delivered I_m Yours.mp3', 1970, N'tevie Wonder')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (10, N'Superstition.mp3', 1972, N'tevie Wonder')
INSERT INTO [dbo].[Song] ([Id], [NameSong], [Year], [Artist]) VALUES (11, N'Sir Duke.mp3', 1976, N'Stevie Wonder')
