//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveUser
    {
        public int User { get; set; }
        public Nullable<int> Score { get; set; }
    }
}
